// Problem statement:

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.


const isEven = (number) => number % 2 === 0

const sumEvenFib = function (upperBound) {
  let [cumulant, fib1, fib2, fibRes] = [2, 1, 2, 0]

  while (fibRes <= upperBound) {
    fibRes = fib2 + fib1;
    [fib2, fib1] = [fibRes, fib2];

    if (isEven(fibRes)) cumulant += fibRes;
  }
  return cumulant;
}
